// Generated by Tools/datagen.swift — do not edit by hand.
// Fetched 2026-09-30.

enum GitHubData {
    /// A column per week, seven rows with Monday at the top.
    static let calendarCounts: [[Int]] = [[0,0,0,0,0,0,1], [11,11,13,10,10,2,0], [5,11,10,10,7,3,1], [1,8,0,0,0,0,0], [0,0,3,3,7,0,0], [4,0,0,0,0,0,0], [0,5,1,2,8,0,0], [4,3,10,6,1,0,0], [8,5,2,3,4,0,0], [2,0,0,0,0,0,0], [0,3,2,3,0,0,5], [8,9,8,18,3,1,0], [5,40,15,8,3,0,0], [0,0,0,0,0,0,0], [0,0,0,0,0,0,1], [0,0,0,0,0,0,0], [6,0,4,0,4,0,0], [2,14,6,2,6,0,0], [3,15,5,8,12,0,0], [6,12,5,5,13,0,0], [15,7,6,9,10,0,3], [2,3,0,3,0,0,0], [4,6,1,21,14,0,6], [14,31,7,16,0,0,0], [2,18,4,10,6,0,0], [5,11,10,12,6,0,0], [28,3,10,2,8,0,0], [27,13,18,13,6,1,0], [0,0,0,0,0,0,0], [0,3,3,15,19,0,0], [17,17,4,14,8,4,0], [9,11,0,5,0,0,0], [3,9,10,4,6,0,0], [13,19,9,8,13,0,1], [5,0,18,31,13,0,1], [8,14,11,10,9,0,0], [0,19,17,17,8,1,0], [8,15,7,10,10,0,3], [12,6,5,11,3,0,0], [27,20,21,4,2,0,0], [16,8,20,15,22,0,2], [0,0,0,0,0,0,0], [0,0,0,0,0,0,0], [8,18,3,7,2,0,0], [4,3,6,19,19,0,2], [7,24,3,26,2,4,0], [20,18,33,15,11,0,0], [30,38,8,14,27,2,0], [7,18,6,11,5,0,0], [5,10,21,20,10,0,0], [7,22,7,6,2,0,0], [3,7,7,13,8,2,0], [11,16,15,9,11,0,14], [11,4,0,0,0,0,0]]

    /// The date each column starts on, aligned with the array above.
    static let calendarWeekStarts = ["2025-09-28", "2025-09-29", "2025-10-06", "2025-10-13", "2025-10-20", "2025-10-27", "2025-11-03", "2025-11-10", "2025-11-17", "2025-11-24", "2025-12-01", "2025-12-08", "2025-12-15", "2025-12-22", "2025-12-29", "2026-01-05", "2026-01-12", "2026-01-19", "2026-01-26", "2026-02-02", "2026-02-09", "2026-02-16", "2026-02-23", "2026-03-02", "2026-03-09", "2026-03-16", "2026-03-23", "2026-03-30", "2026-04-06", "2026-04-13", "2026-04-20", "2026-04-27", "2026-05-04", "2026-05-11", "2026-05-18", "2026-05-25", "2026-06-01", "2026-06-08", "2026-06-15", "2026-06-22", "2026-06-29", "2026-07-06", "2026-07-13", "2026-07-20", "2026-07-27", "2026-08-03", "2026-08-10", "2026-08-17", "2026-08-24", "2026-08-31", "2026-09-07", "2026-09-14", "2026-09-21", "2026-09-28"]

    static let repos: [Repo] = [
        Repo(full: "matrix-org/matrix-rust-sdk", blurb: "Matrix Client-Server SDK for Rust", stars: 2316, forks: 509, language: "Rust", prs: 164),
        Repo(full: "element-hq/element-ios", blurb: "Element's Classic app for Matrix collaboration on iOS", stars: 1841, forks: 547, language: "Swift", prs: 139),
        Repo(full: "matrix-org/matrix-spec-proposals", blurb: "Proposals for changes to the matrix specification", stars: 1256, forks: 454, language: "Python", prs: 5),
        Repo(full: "stefanceriu/SCSiriWaveformView", blurb: "UIView subclass that reproduces the waveform effect seen in Siri on iOS 7.", stars: 1096, forks: 119, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCXcodeMiniMap", blurb: "Sublime Text like Minimap for Xcode", stars: 1013, forks: 85, language: "Objective-C", prs: 0),
        Repo(full: "element-hq/element-x-ios", blurb: "Next generation Matrix client for iOS built with SwiftUI on top of matrix-rust-sdk.", stars: 947, forks: 384, language: "Swift", prs: 996),
        Repo(full: "stefanceriu/SCXcodeSwitchExpander", blurb: "Xcode plugin that enables switch cases autocompletion", stars: 651, forks: 96, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCStringsUtility", blurb: "OS X / iOS Translations helper", stars: 524, forks: 48, language: "Objective-C", prs: 0),
        Repo(full: "matrix-org/matrix-ios-sdk", blurb: "The Matrix SDK for iOS", stars: 484, forks: 225, language: "Objective-C", prs: 51),
        Repo(full: "stefanceriu/SCSafariPageController", blurb: "A page view controller component that reproduces Mobile Safari's tab switching behavior", stars: 383, forks: 49, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCPageViewController", blurb: "Just like UIPageViewController but better.. :)", stars: 350, forks: 69, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCStackViewController", blurb: "SCStackViewController is a container view controller which allows you to stack other view controllers on the  top/left/bottom/right of the root and build custom transitions between them while providing correct physics and appearance calls.", stars: 263, forks: 17, language: "Objective-C", prs: 0),
        Repo(full: "matrix-org/matrix-ios-kit", blurb: "Reusable UI interfaces to ease building of Matrix client apps", stars: 126, forks: 70, language: "Objective-C", prs: 17),
        Repo(full: "stefanceriu/SCSkypeActivityIndicatorView", blurb: "Activity indicator view similar to the one seen in the Skype apps.", stars: 102, forks: 19, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCXcodeEditorInset", blurb: "Xcode plugin that adds an empty (configurable) space to the end of the editor text view", stars: 63, forks: 4, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCNavigationController", blurb: "SCNavigationController is an UINavigationController like container view controller and was built to provide and expose more features and control", stars: 44, forks: 4, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCXcodeTabSwitcher", blurb: "Enables changing Xcode tabs using the ⌘cmd + [1..9] keys", stars: 42, forks: 2, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCScrollView", blurb: "UIScrollView subclass that can use a custom easing function to animate the setting of the content offset", stars: 20, forks: 9, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/Xcode-Headers", blurb: "Xcode headers dump", stars: 19, forks: 3, language: "Objective-C", prs: 0),
        Repo(full: "matrix-org/complement-crypto", blurb: "", stars: 18, forks: 12, language: "Go", prs: 6),
        Repo(full: "stefanceriu/UIScrollView-ScrollerAdditions", blurb: "Customising UIScrollView's scroll bars", stars: 17, forks: 6, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCDragController", blurb: "SCDragController is a component meant to aid the development of drag & drop behaviors.", stars: 10, forks: 2, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCMarsRover", blurb: "Simple cocoa application that provides a visual implementation to the Thoughtworks Mars Rover problem", stars: 1, forks: 0, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/stefanceriu.github.io", blurb: "", stars: 0, forks: 0, language: "Swift", prs: 0),
        Repo(full: "stefanceriu/SCEdgeStack", blurb: "A SwiftUI container that stacks child views off the top, leading, bottom and trailing edges of a root view, driving their frames and transforms from the content offset of a hidden `UIScrollView`.", stars: 0, forks: 0, language: "Swift", prs: 0),
        Repo(full: "stefanceriu/stefanceriu", blurb: "", stars: 0, forks: 0, language: "", prs: 0),
        Repo(full: "stefanceriu/Test", blurb: "", stars: 0, forks: 0, language: "", prs: 0),
        Repo(full: "stefanceriu/WebMediaStreamWithCallKit", blurb: "Sample project that demonstrates web MediaStream <-> CallKit integration issues", stars: 0, forks: 0, language: "Swift", prs: 0),
        Repo(full: "stefanceriu/swifthub", blurb: "", stars: 0, forks: 0, language: "Swift", prs: 0),
    ]

    static let orgTotals: [(org: String, count: Int)] = [("element-hq", 1149), ("matrix-org", 246)]

    static let orgPullRequests: [(repo: String, count: Int)] = [("element-hq/element-x-ios", 996), ("matrix-org/matrix-rust-sdk", 164), ("element-hq/element-ios", 139), ("matrix-org/matrix-ios-sdk", 51), ("matrix-org/matrix-ios-kit", 17), ("matrix-org/complement-crypto", 6), ("matrix-org/matrix-spec-proposals", 5)]
}
