// Generated by Tools/datagen.swift — do not edit by hand.
// Fetched 2026-08-31.

enum GitHubData {
    /// A column per week, seven rows with Monday at the top.
    static let calendarCounts: [[Int]] = [[0,0,0,0,0,0,0], [0,0,0,0,0,0,0], [3,7,10,8,18,0,0], [3,15,3,6,10,0,2], [6,7,12,5,13,0,1], [10,10,14,9,10,1,0], [5,10,6,9,6,2,1], [1,6,0,0,0,0,0], [0,0,3,3,7,0,0], [2,0,0,0,0,0,0], [0,5,1,2,5,0,0], [3,3,7,6,1,0,0], [7,5,2,3,3,0,0], [2,0,0,0,0,0,0], [0,3,2,3,0,0,4], [8,8,7,12,3,1,0], [5,31,12,6,3,0,0], [0,0,0,0,0,0,0], [0,0,0,0,0,0,1], [0,0,0,0,0,0,0], [4,0,4,0,4,0,0], [2,12,5,2,6,0,0], [2,11,3,7,10,0,0], [4,9,4,4,10,0,0], [12,6,5,8,9,0,2], [2,2,0,2,0,0,0], [4,5,1,17,10,0,3], [9,31,6,15,0,0,0], [2,17,4,9,6,0,0], [5,11,10,8,6,0,0], [21,3,10,1,4,0,0], [18,9,13,9,6,1,0], [0,0,0,0,0,0,0], [0,2,2,10,12,0,0], [12,13,4,14,5,3,0], [7,8,0,4,0,0,0], [3,7,9,4,6,0,0], [9,18,7,6,10,0,1], [5,0,13,21,9,0,1], [5,12,8,6,7,0,0], [0,11,11,11,7,1,0], [5,12,7,8,8,0,2], [7,6,4,9,2,0,0], [18,15,15,2,2,0,0], [12,5,13,10,16,0,2], [0,0,0,0,0,0,0], [0,0,0,0,0,0,0], [5,11,2,6,2,0,0], [3,3,5,14,11,0,2], [7,18,3,7,2,3,0], [15,13,20,11,8,0,0], [7,23,6,9,21,2,0], [6,10,5,10,6,0,0], [0,0,0,0,0,0,0]]

    /// The date each column starts on, aligned with the array above.
    static let calendarWeekStarts = ["2025-08-31", "2025-09-01", "2025-09-08", "2025-09-15", "2025-09-22", "2025-09-29", "2025-10-06", "2025-10-13", "2025-10-20", "2025-10-27", "2025-11-03", "2025-11-10", "2025-11-17", "2025-11-24", "2025-12-01", "2025-12-08", "2025-12-15", "2025-12-22", "2025-12-29", "2026-01-05", "2026-01-12", "2026-01-19", "2026-01-26", "2026-02-02", "2026-02-09", "2026-02-16", "2026-02-23", "2026-03-02", "2026-03-09", "2026-03-16", "2026-03-23", "2026-03-30", "2026-04-06", "2026-04-13", "2026-04-20", "2026-04-27", "2026-05-04", "2026-05-11", "2026-05-18", "2026-05-25", "2026-06-01", "2026-06-08", "2026-06-15", "2026-06-22", "2026-06-29", "2026-07-06", "2026-07-13", "2026-07-20", "2026-07-27", "2026-08-03", "2026-08-10", "2026-08-17", "2026-08-24", "2026-08-31"]

    static let repos: [Repo] = [
        Repo(full: "matrix-org/matrix-rust-sdk", blurb: "Matrix Client-Server SDK for Rust", stars: 2265, forks: 485, language: "Rust", prs: 151),
        Repo(full: "element-hq/element-ios", blurb: "A glossy Matrix collaboration client for iOS", stars: 1841, forks: 542, language: "Swift", prs: 139),
        Repo(full: "matrix-org/matrix-spec-proposals", blurb: "Proposals for changes to the matrix specification", stars: 1250, forks: 448, language: "", prs: 5),
        Repo(full: "stefanceriu/SCSiriWaveformView", blurb: "UIView subclass that reproduces the waveform effect seen in Siri on iOS 7.", stars: 1096, forks: 120, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCXcodeMiniMap", blurb: "Sublime Text like Minimap for Xcode", stars: 1015, forks: 85, language: "Objective-C", prs: 0),
        Repo(full: "element-hq/element-x-ios", blurb: "Next generation Matrix client for iOS built with SwiftUI on top of matrix-rust-sdk.", stars: 932, forks: 365, language: "Swift", prs: 973),
        Repo(full: "stefanceriu/SCXcodeSwitchExpander", blurb: "Xcode plugin that enables switch cases autocompletion", stars: 652, forks: 96, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCStringsUtility", blurb: "OS X / iOS Translations helper", stars: 524, forks: 48, language: "Objective-C", prs: 0),
        Repo(full: "matrix-org/matrix-ios-sdk", blurb: "The Matrix SDK for iOS", stars: 484, forks: 226, language: "Objective-C", prs: 51),
        Repo(full: "stefanceriu/SCSafariPageController", blurb: "A page view controller component that reproduces Mobile Safari's tab switching behavior", stars: 384, forks: 49, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCPageViewController", blurb: "Just like UIPageViewController but better.. :)", stars: 350, forks: 70, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCStackViewController", blurb: "SCStackViewController is a container view controller which allows you to stack other view controllers on the  top/left/bottom/right of the root and build custom transitions between them while providing correct physics and appearance calls.", stars: 263, forks: 17, language: "Objective-C", prs: 0),
        Repo(full: "matrix-org/matrix-ios-kit", blurb: "Reusable UI interfaces to ease building of Matrix client apps", stars: 126, forks: 70, language: "Objective-C", prs: 17),
        Repo(full: "stefanceriu/SCSkypeActivityIndicatorView", blurb: "Activity indicator view similar to the one seen in the Skype apps.", stars: 103, forks: 19, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCXcodeEditorInset", blurb: "Xcode plugin that adds an empty (configurable) space to the end of the editor text view", stars: 63, forks: 4, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCNavigationController", blurb: "SCNavigationController is an UINavigationController like container view controller and was built to provide and expose more features and control", stars: 44, forks: 4, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCXcodeTabSwitcher", blurb: "Enables changing Xcode tabs using the ⌘cmd + [1..9] keys", stars: 42, forks: 2, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCScrollView", blurb: "UIScrollView subclass that can use a custom easing function to animate the setting of the content offset", stars: 20, forks: 9, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/Xcode-Headers", blurb: "Xcode headers dump", stars: 19, forks: 3, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/UIScrollView-ScrollerAdditions", blurb: "Customising UIScrollView's scroll bars", stars: 17, forks: 6, language: "Objective-C", prs: 0),
        Repo(full: "matrix-org/complement-crypto", blurb: "", stars: 17, forks: 12, language: "Go", prs: 6),
        Repo(full: "stefanceriu/SCDragController", blurb: "SCDragController is a component meant to aid the development of drag & drop behaviors.", stars: 10, forks: 2, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/SCMarsRover", blurb: "Simple cocoa application that provides a visual implementation to the Thoughtworks Mars Rover problem", stars: 1, forks: 0, language: "Objective-C", prs: 0),
        Repo(full: "stefanceriu/stefanceriu", blurb: "", stars: 0, forks: 0, language: "", prs: 0),
        Repo(full: "stefanceriu/Test", blurb: "", stars: 0, forks: 0, language: "", prs: 0),
        Repo(full: "stefanceriu/WebMediaStreamWithCallKit", blurb: "Sample project that demonstrates web MediaStream <-> CallKit integration issues", stars: 0, forks: 0, language: "Swift", prs: 0),
        Repo(full: "stefanceriu/swifthub", blurb: "", stars: 0, forks: 0, language: "Swift", prs: 0),
        Repo(full: "stefanceriu/stefanceriu.github.io", blurb: "", stars: 0, forks: 0, language: "", prs: 0),
    ]

    static let orgTotals: [(org: String, count: Int)] = [("element-hq", 1126), ("matrix-org", 233)]

    static let orgPullRequests: [(repo: String, count: Int)] = [("element-hq/element-x-ios", 973), ("matrix-org/matrix-rust-sdk", 151), ("element-hq/element-ios", 139), ("matrix-org/matrix-ios-sdk", 51), ("matrix-org/matrix-ios-kit", 17), ("matrix-org/complement-crypto", 6), ("matrix-org/matrix-spec-proposals", 5), ("element-hq/element-x-android", 1), ("element-hq/synapse", 1)]
}
